# Generated by Django 5.2.11 on 2026-04-03 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('finished', 'Finished')], default='confirmed', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_document', models.CharField(max_length=50)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
    ]
