# Generated by Django 5.2.11 on 2026-04-23 03:40

from django.db import migrations

def create_receptionist_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')#obtione el modelo Group de la aplicacion auth
    Group.objects.get_or_create(name= 'Receptionist')#busca o crea si no existe

def remove_receptionist_group(apps, schema_editor):#se debe crear por si se revierte la migración 
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Receptionist').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ("auth", "0012_alter_user_first_name_max_length"),#esta se usa para asegurarse que antes de ejecutar esta migracion el modelo Group este disponible
    ]

    operations = [
        migrations.RunPython(create_receptionist_group, remove_receptionist_group)
    ]
