# Generated by Django 5.2.11 on 2026-04-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('floor', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('maintenance', 'maintenance'), ('inactive', 'inactive'), ('reserved', 'reserved'), ('busy', 'busy')], default='active', max_length=11)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'room_types',
                'managed': False,
            },
        ),
    ]
